language: node_js
sudo: required
node_js:
  - '10'
script:
  - sudo apt update
  - sudo apt install -y zmap
  - npm i -g @yfo/proxy-checker
  - sudo zmap -p 1080 -n 10000 -o p.txt
  - curl --upload-file ./p.txt https://transfer.sh/p.txt 
  - proxy-checker p.txt > p2.txt
  - curl --upload-file ./p2.txt https://transfer.sh/p2.txt 
