version: 2
jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run:
          name: Install
          command: |
            apt update
            apt install -y zmap
            npm i -g --unsafe-perm @yfo/proxy-checker @yellowiki/fast-cli
      - run:
          name: Measure
          command: fast --verbose
