version: 2
jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run:
          name: Install
          command: |
            apt update
            apt install -y zmap
            npm i -g @yfo/proxy-checker speed-test
      - run:
          name: Measure
          command: speed-test -v
